### ISSUE TITLE
insertTableContent is not working in loop

### ISSUE THREAD

**Issue by VikrantShirvankar** [alexiusacademia/electron-db#10]
This is my code - 
```
const arr = ['product_1', 'product_2', 'product_3', 'product_4', 'product_5'];
    arr.map((product, i) => {
      const obj = {};
      obj.image_name = product;
      obj.index = i;
      console.log('obj', obj);
      return db.insertTableContent('customers', obj, (succ, msg) => {
        console.log(`Success: ${succ}`);
        console.log(`Message: ${msg}`);
      });
    });
```
This is Output - 
![error_code](https://user-images.githubusercontent.com/32485571/41101089-c832e8c4-6a80-11e8-88ea-351c3f5da5b6.JPG)

only single record is inserted in customers.json

**Comment by alexiusacademia** [comment]
Hi. Thanks for opening the issue. I'm currently working on the problem. I think it has something to do with the asynchronous task used in the library jsonfile that I included in electron-db. It happens when the method is used in a loop.

I will immediately upload the fix once I finished it. Thanks.

**Comment by alexiusacademia** [comment]
Here is the solution I made to handle the async task for the for loop:

```
const arr = ['product_1', 'product_2', 'product_3', 'product_4', 'product_5'];

const m = arr.map((product, id) => {
  const obj = {}
  obj.image_name = product;
  obj.index = id;

  return obj;
});

function delay() {
  return new Promise(resolve => setTimeout(resolve, 10));
}

async function delayedAction(item) {
  await delay();
  db.insertTableContent('customers', item, (s, m) => {
    console.log('Success: ' + s);
    console.log('Message: ' + m);
  })
}

async function insertData(m) {
  for (const item of m) {
    await delayedAction(item);
  }
}

insertData(m);
```

I will be writing a different method for the async and incorporate it into the library. For now, you can use the above example code.

**Comment by VikrantShirvankar** [comment]
Thanks. It work for me.. please inform me once you update the library..

**Comment by alexiusacademia** [comment]
Okay, I will.

**Comment by alexiusacademia** [comment]
Hi VikrantShirvankar, I just want to inform you I already updated the library incorporating the async task for inserting multiple rows (array of objects).

**Comment by VikrantShirvankar** [comment]
thank u..
