### ISSUE TITLE
getAll return false

### ISSUE THREAD

**Issue by ducaiwei** [alexiusacademia/electron-db#11]
when I insert table success, I getAll data immediately, but getAll return false.
db.insertTableContent(obj).then(res => {
   db.getAll('tables') // return false
})

**Comment by alexiusacademia** [comment]
Hi there. You should call db.getAll in a separate statement to reflect the actual result. To shed more light, can you please post the actual or similar code u used with sample data for it to be confirmed? Thanks

**Comment by ducaiwei** [comment]
Thanks. It work for me. 
Reference this question: #10 . Handle an async task before getAll.
