### ISSUE TITLE
BUG - getAll example uses incorrect syntax

### ISSUE THREAD

**Issue by Skullsneeze** [alexiusacademia/electron-db#15]
I found that the example for the `getAll` method uses an incorrect syntax.

**Current syntax:**

```
db.getAll('customers', (succ, data)) {
  // succ - boolean, tells if the call is successful
  // data - array of objects that represents the rows.
}
```

**Corrected syntax:**

```
db.getAll('customers', (succ, data) => {
  // succ - boolean, tells if the call is successful
  // data - array of objects that represents the rows.
});
```

**Comment by alexiusacademia** [comment]
Thanks for pointing that out. However, this is not a bug in the code but a typo error in the example so I cannot mark it as bug.

**Comment by Skullsneeze** [comment]
Good point! Wasn't sure how to mark it in this case. Glad to be able to help though, and thank you for providing this awesome extension 👍

**Comment by alexiusacademia** [comment]
I'm glad this library helps. I am gonna be adding and updating features this coming weeks. If you have any enhancements in mind, I'm glad to know about it.Thanks!
