### ISSUE TITLE
UpdateRow Error

### ISSUE THREAD

**Issue by MinaMourice** [alexiusacademia/electron-db#17]
UpdateRow function check first row only 

```
for (var i = 0; i < rows.length; i++) { 
.
.
.
else {
        callback(false, "Cannot find the specified record.");
        return;
}

}
```

when it enter the else condition of "Cannot find the specified record" it execute return without continuing to check the remaining rows

**Comment by alexiusacademia** [comment]
This bug has been fixed but I mistakenly made it by using the old file. Not it is fixed at [079230e](https://github.com/alexiusacademia/electron-db/commit/079230eec098470a2fe237be58adf0ad951803ac) and was published at version 0.9.1

Thanks!
