### ISSUE TITLE
Problem app.asar.unpacked

### ISSUE THREAD

**Issue by rafaelvaloto** [alexiusacademia/electron-db#18]
An error occurred while trying to read the package.json file, it seems to me that it is not able to read in the ../resources/app.asar directory.
Here's the line I'm compiling.
electron-packager. Neoprinter --icon = icon.png --platform = linux --arch x64 --out dist / --overwrite
Follow the error
![Seleção_060](https://user-images.githubusercontent.com/6644601/54284235-51146e00-457e-11e9-8813-58fc2e85aa81.png)

It seems that you are missing the dependency to read packages 
[asar](https://electronjs.org/docs/tutorial/application-packaging#tratando-um-pacote-asar-como-um-arquivo-normal)

commenting on the following lines from the index.js file, the application worked correctly after compiling

`let appName = 'Neoprinter';`
`/* if (JSON.parse(fs.readFileSync('package.json', 'utf-8')).productName) {
  appName = JSON.parse(fs.readFileSync('package.json', 'utf-8')).productName;
}else{
  appName = JSON.parse(fs.readFileSync('package.json', 'utf-8')).name;
} */`

I need help

**Comment by alexiusacademia** [comment]
Hello rafaelvaloto, sorry for the late reply. It's been a busy week for me. 

As for your issue, I haven't worked with asar yet from the past but I will be looking at it this coming week and hopefully make a solution for your problem soon.

**Comment by dipeshparashar** [comment]
I Confirm the issue mentioned [above ](https://github.com/electron-userland/electron-packager/issues/981).  Please fix it at the earliest if possible. I am not sure what will be the best replacement of Electron-DB in my current project.

**Comment by rafaelvaloto** [comment]
> I Confirm the issue mentioned [above ](https://github.com/electron-userland/electron-packager/issues/981). Please fix it at the earliest if possible. I am not sure what will be the best replacement of Electron-DB in my current project.

@dipeshparashar ,
You can temporarily fix this in the `node_modules/electron-db /index.js` file of the electron-DB package, comment out the lines and manually adding a name in the var appName
`let appName = 'NameApp';`
`/* if (JSON.parse(fs.readFileSync('package.json', 'utf-8')).productName) { appName = JSON.parse(fs.readFileSync('package.json', 'utf-8')).productName; }else{ appName = JSON.parse(fs.readFileSync('package.json', 'utf-8')).name; } */`

And recompiling your app again ...

**Comment by alexiusacademia** [comment]
This has been fixed now. You may use the latest version ```0.11.1```. The bug was when using the ```fs``` and the one as stated above. Now replaced by reading the ```package.json``` by importing it directly and using the ```name``` property which should be provided.
