### ISSUE TITLE
Any way to drop entire table?

### ISSUE THREAD

**Issue by stuible** [alexiusacademia/electron-db#19]
Great looking project, would love a way to remove all rows of a table or drop the table completely.

**Comment by alexiusacademia** [comment]
As of now, deleting the entire file is not yet available but will be implemented in future versions. For now, you can just manually iterate through all the rows and delete them iteratively.

**Comment by alexiusacademia** [comment]
Hi there. Apology for late update. The feature is now added in version 
[```v0.13.1```](https://www.npmjs.com/package/electron-db)
