### ISSUE TITLE
Table exists?

### ISSUE THREAD

**Issue by xortrike** [alexiusacademia/electron-db#24]
It would be nice if there was a method for checking the existence of a table.
Because if I try to check a non-existing table using the "valid" method, I get an error.
Please add method for check table or extend the "valid" method, adding this checking.
`if ( fs.existsSync(fName) === false ) {
    return false;
}`

**Comment by alexiusacademia** [comment]
Hi @xortrike, thank you for the suggestion. Please note that you are welcome to fork the project and add your desired functionality then create a pull request.

I would love that more people could collaborate with this project. Although I will take a look at this when I got available time.

Thanks and regards!
