### ISSUE TITLE
getField should return false for invalid field/key

### ISSUE THREAD

**Issue by BryanYeh** [alexiusacademia/electron-db#26]
Shouldn't `getField()` return **false** when the field/key doesn't exists?
It is tripping me out when it returns an empty array.

**Comment by alexiusacademia** [comment]
It's probably right. I will be addng a fix to it. Thanks for pointing that one out.

**Comment by alexiusacademia** [comment]
I just published version 0.15.3 reflecting that patch. Thank you.
