### ISSUE TITLE
Typo in variable of valid() function

### ISSUE THREAD

**Issue by smithersmc** [alexiusacademia/electron-db#27]
Hi,
Thanks for this great library. I believe there is a small typo in the valid() function that causes an error "ENOENT: no such file or directory" for me.

```
  if (arguments.length == 2) {
        // Given the database name and location
        const dbName = arguments[0]
        const dbLocation = arguments[1]
        var fName = path.join(dbLocation, dbName + '.json')
    } else if (arguments.length == 1) {
        const dbName = arguments[0]
        fname = path.join(userData, dbName + '.json')
    }
```

Last `fname` shall be `fName` instead. I am not familiar with git yet, so if you want to fix it...
Christian

**Comment by VikashLoomba** [comment]
My PR that fixes this was merged in. This can be closed

**Comment by alexiusacademia** [comment]
Yes thank you for that.
