### ISSUE TITLE
Feature Request: Allow functions as where statements

### ISSUE THREAD

**Issue by jarethuk** [alexiusacademia/electron-db#32]
Hi,

I have the following data structure and want to be able to get records where it has a tag e.g. string value in an array.

`
{
name: 'something',
tags: ['test', 'test2']
}
`

I thought the most generic way of doing this would be to allow functions to be passed in as the where clause (much like .filter in js).

Thoughts?

Jareth

**Comment by alexiusacademia** [comment]
Thanks for this. But I think it's best and simpler if the where clause is an object for this library. Thanks.

**Comment by jarethuk** [comment]
Simpler yes, but doesn't allow me to solve my problem of filtering by values in an array.

**Comment by alexiusacademia** [comment]
Hi @jarethuk , I would much appreciate it if you'd give me some use case. Maybe I could add some callback functionality or something that might be appropriate for those cases. Thanks
