### ISSUE TITLE
i got a problem at getRow(s) 

### ISSUE THREAD

**Issue by azwc** [alexiusacademia/electron-db#34]
db file is ‘novel.json’, it's no data.

**cond:**
```
 { author: 'xx', source: 'xxx.cc', title: 'test' }
```
**Query:**
```
db.getRows('novel', location, cond, (succ, msg) => {
    console.log(succ);
    console.log(msg);
}
```
**Output:**
```
true
[]
```
Why?

**Comment by alexiusacademia** [comment]
wht do you mean by it's no data?

**Comment by azwc** [comment]
> wht do you mean by it's no data?

novel.json
```
{
    "novel":[]
}
```
query by cond,expect false,but i got true.i thought true is that data exists,is not it?

**Comment by alexiusacademia** [comment]
True means it can be queried. The fact that the file exist means it can be. Empty result indicates that there are no results returned. Zero matching the query.
