### ISSUE TITLE
[BUG] DeleteRow

### ISSUE THREAD

**Issue by isidoor** [alexiusacademia/electron-db#39]
Hello ! 

DeleteRow function is not working when there are multiple matchs to delete.

current code is : 

`            for (let k = 0; k < matchedIndices.length; k++) {
                rows.splice(matchedIndices[k], 1);
            }
`

matchedIndices = [0,1,2]
rows:  [ a, b, c ]

1. first splice delete a, rows => [b, c]
2. second splice delete c, rows = [b]
3. last splice delete nothing

maybe this should correct the code

`            for (let k = matchedIndices.length; k >= 0; k--) {
                rows.splice(matchedIndices[k], 1);
            }
`

**Comment by alexiusacademia** [comment]
Hello and good day!

Thank for your suggestion. However I cannot work on this right now. I would much appreciate it and you are very welcome to create a pull request regarding this matter.

Thank you!

**Comment by Sanan4li** [comment]
As the maintainer of the package is not maintaining this anymore. I have created the same package like this with a lot more features and fixed all the bugs. 
https://www.npmjs.com/package/json-local-database
