### ISSUE TITLE
Broken Json issue

### ISSUE THREAD

**Issue by LordRampantHump** [alexiusacademia/electron-db#43]
sometimes i get this broken json issue normally if two workers try write at the same time i guess:

`{
  "accounts": [
    {
      "uuid": "7q9cMDq1ax9i2iEkKenKtf",
      "firstName": "Gene",
      "lastName": "West",
      "gender": "male",
      "email": "Gene_West19@gmail.com",
      "password": "JYoETNE7SjdkIyO",
      "avatarSet": false,
      "passwordChanged": false,
      "listening": false,
      "id": 1625479565120
    }
  ] <------ extra square bracket
}
  ] 
}`

is there any function to repair the json should this issue happen for any reason

**Comment by alexiusacademia** [comment]
Actually, the extra square bracket you're pointing at is the correct placement of that bracket, that's after the object account.
