### ISSUE TITLE
How would you remove a database item?

### ISSUE THREAD

**Issue by LauraWebdev** [alexiusacademia/electron-db#5]
Hey, very good library so far, I really like the simplicity!

What I was not able to get working so far though is removing items from the database. The documentation does not include an example for that either.

**Comment by alexiusacademia** [comment]
Hi there. The library doesn't include the delete row functionality until now. Thanks for opening the issue. You can now use this functionality using

```javascript

const db = require('electron-db');
const electron = require('electron');

db.deleteRow('customers', {'id': 1508419374272}, (succ, msg) => {
  console.log(msg);
});
```
