### ISSUE TITLE
"update" seems do not work well

### ISSUE THREAD

**Issue by qianliuGit** [alexiusacademia/electron-db#8]
// 修改节点名称
ipc.on('renameNode', (event, arg) => {
    console.log('renameNode...')
    console.log('id: ' + arg.id)
    console.log('text: ' + arg.text)

    let where = {
        'id': arg.id
    }

    let set = {
        'text': arg.text
    }

    db.updateRow(ORGTABELE, where, set, (succ, msg) => {
        console.log('update...')
        console.log('succ: ' + succ)
        console.log('msg: ' + msg)
    })
})

------------------output --------------------------------

renameNode...
id: 1528010777034
text: dfd
update...
succ: false
msg: Cannot find the specified record.
update...
succ: false
msg: Cannot find the specified record.

**Comment by alexiusacademia** [comment]
Hello [qianliuGit](https://github.com/qianliuGit), it looks that your implementation is right, however, based on the message displayed by the callback, there are 2 possible reasons for the error; one is that there are no matched keys or that the table structure is not according to the generated structure if you used electron-db on generating the rows.

Please tell me that you have data and structure to the json below:
say your table name is "ORGTABELE";
*ORGTABELE.json*
```json
{
  "ORGTABELE": [
    {
      "id": "1528010777034",
      "text": "Something else...",
      ...
    }
  ]
}
```

**Comment by alexiusacademia** [comment]
Does the other db commands works on your json file? Could you send me the conents or part of the file? Thanks.

**Comment by qianliuGit** [comment]
Thanks a lot
